Support additional image types
containers/krunkit pull request #22
Opened 2024-12-17 22:14 UTC by jakecorrenti

Extend the command line to support the new `krun_add_disk2` API in libkrun. This will allow the user to specify non-Raw disk image formats. The list of supported disk image formats is now: Raw, Qcow2.

2024-12-17 22:15 UTC, jakecorrenti commented
Keeping this a draft for the time being since libkrun doesn't have a release cut with the Qcow2 commits

2024-12-18 03:32 UTC, tylerfanelli requested changes

2024-12-18 03:32 UTC, tylerfanelli commented on src/virtio.rs
> +pub const KRUN_DISK_FORMAT_QCOW2: u32 = 1;
I think an enum should represent this:

```
enum DiskImageFormat {
    Raw,
    Qcow2
}

impl From<DiskImageFormat> for u32 {
    fn from(d: DiskImageFormat) -> u32 {
        match d {
            DiskImageFormat::Raw => 1,
            DiskImageFormat::Qcow2 => 2,
        }
    }
}
```

and then also implement `FromStr` for `DiskImageFormat` for the command line.

2024-12-18 03:34 UTC, tylerfanelli commented
I think you can squash commits so there are just two. One for the implementation, and one for the documentation.

2024-12-18 14:06 UTC, jakecorrenti commented on src/virtio.rs
> +pub const KRUN_DISK_FORMAT_QCOW2: u32 = 1;
Should be fixed now. Thanks!

2024-12-18 15:32 UTC, tylerfanelli commented on src/virtio.rs
> +            "qcow2" => Ok(DiskImageFormat::Qcow2),
I want to say we should probe the actual image to see if its qcow2, but I *think* there was discussion in the libkrun PR that this should be avoided, right?

2024-12-18 15:33 UTC, jakecorrenti commented on src/virtio.rs
> +            "qcow2" => Ok(DiskImageFormat::Qcow2),
Yes, we should avoid probing at all costs. That's my understanding of it.

2024-12-18 15:34 UTC, tylerfanelli commented on src/virtio.rs
> +            "qcow2" => Ok(DiskImageFormat::Qcow2),
In that case, this LGTM. Nice work!

2024-12-18 15:34 UTC, tylerfanelli approved these changes
LGTM. We'll wait for the libkrun release.

2025-01-17 14:20 UTC, jakecorrenti commented
libkrun 1.10 got released, so marking this as ready for review

2025-01-17 18:58 UTC, merged